In [3]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**FILTRO 1- BUSQUEDA POR OBJETO**
Este filtro es utilizado para buscar puntualmente un dato dentro de alguna columna.
 En el script logramos seleccionar la variable "*NOMBRE_CLIENTE*" de la cual nos interesa ubicar las transacciones realizadas por "*MOLINERA DE MEXICO*".

In [5]:
filtro1=df[df["NOMBRE_CLIENTE"] == "MOLINERA DE MEXICO"]
filtro1
filtro1.to_csv("Filtro1.csv")

**FILTRO 2- BUSCAR POR FILAS**
Utilizado para buscar especificamente alguna fila o renglón, en este caso haremos búsqueda de las filas 14, 98 y 250.

In [6]:
filtro2=df.iloc[ [14, 98, 250] , : ]
filtro2
filtro2.to_csv("Filtro2.csv")

**FILTRO 3 - BUSCAR POR COLUMNAS**
Similar al filtro anterior solo que en este caso está destinado a buscar por columnas.

In [7]:
filtro3=df.iloc[ : , [2, 4]]
filtro3
filtro3.to_csv("Filtro3.csv")

**FILTRO 4 - BUSQUEDA CRUZADA**
En este filtro buscamos algún dato con filas y columnas específicas.
 En el script buscamos localizar las transacciones registradas por "*ALFREDO CANELA*" y el "*MARGEN TOTAL CALCULADO*"

In [8]:
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=2)
df1

,CVE_DOC,FECHA_DOC,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
NOMBRE_VENDEDOR,,,,,,,,,,,,,
LETICIA RAMIREZ HERNANDEZ,F37034,2022-01-05,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
LETICIA RAMIREZ HERNANDEZ,F37036,2022-01-05,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
DIEGO ARMANDO LEON DURAN,F37041,2022-01-05,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
DIEGO ARMANDO LEON DURAN,F37042,2022-01-05,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
LETICIA RAMIREZ HERNANDEZ,F37043,2022-01-05,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
LETICIA RAMIREZ HERNANDEZ,F39834,2022-12-23,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
LETICIA RAMIREZ HERNANDEZ,F39834,2022-12-23,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
LETICIA RAMIREZ HERNANDEZ,F39835,2022-12-23,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
LETICIA RAMIREZ HERNANDEZ,F39837,2022-12-23,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
AARON NUÑO CORDOVA,F39838,2022-12-23,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [20]:
filtro4=df1.loc[["ALFREDO CANELA"],["MARGEN_TOTAL_CALCULADO"]]
filtro4
filtro4.to_csv("Filtro4.csv")

                 MARGEN_TOTAL_CALCULADO
NOMBRE_VENDEDOR
ALFREDO CANELA                  3713.02
ALFREDO CANELA                  5218.69
ALFREDO CANELA                  1406.76
ALFREDO CANELA                 29816.42
ALFREDO CANELA                  3364.80
...                                 ...
ALFREDO CANELA                  3806.75
ALFREDO CANELA                  4349.11
ALFREDO CANELA                  2200.32
ALFREDO CANELA                 10637.54
ALFREDO CANELA                  7920.92

[335 rows x 1 columns]

**FILTRO 5 - BÚSQUEDA POR CABECERA**
Utilizado para realizar búsquedad de los elementos iniciales de un data frame.

In [12]:
filtro5=df1.head(10)
filtro5
filtro5.to_csv("Filtro5.csv")

**FILTRO 6 - BÚSQUEDA POR COLA** En este fitro filtramos las filas finales del data frame

In [ ]:
filtro6=df1.tail(10)
filtro6
filtro6.to_csv("Filtro6.csv")

**FILTRO 7- COMPARACIÓN**
Este es utilizado para comparar datos cuantitativos siendo que, podríamos realizar operaciones aritméticas básicas.
 En este script decidimos averiguar cual es el mejor de los clientes en el registro, por lo cual procedemos a averiguar cuales de estos han gastado mas de $60,000 en las transacciones.

In [26]:
filtro7=df[df["MARGEN_TOTAL_CALCULADO"] > 60000]
filtro7
filtro7.to_csv("Filtro7.csv")

**FILTRO 8 - FILTRO LÓGICO AND** 
Este es utilizado para condicionar 2 situaciones dodne ambas deben suceder simultanemanete. 
 En el script nos interesa localizar transcacciones donde se venden mas de 30 artículos y son realizadas por *ALFREDO CANELA*.

In [44]:
filtro8=df[(df["CANT"] > 20) & (df["NOMBRE_VENDEDOR"] == "ALFREDO CANELA")]
filtro8
filtro8.to_csv("Filtro8.csv")

**FILTRO 9 - FILTRO LÓGICO OR** 
Este filtro lo utilizamos cuando necesitamos cumplir con características de búsqueda en específico de una u otra situación. 
 En este script buscamos información donde las transaaciones realizadas registran ventas de mas de 30 artículos o ventas realizadas por ALFREDO CANELA.

In [43]:
filtro9=df[(df["CANT"] > 30) | (df["NOMBRE_VENDEDOR"] == "ALFREDO CANELA")]
filtro9
filtro9.to_csv("Filtro9.csv")

**FILTRO 10 - FILTRO LÓGICO NOT** 
Se utiliza para excluir información de búsqueda. 
 Vamos a utilizar algo de los ejemplos anteriores y buscaremos transacciones donde no se vendan menos de 20 artículos y donde ALFREDO CANELA no haya realizado la venta.

In [46]:
filtro10=df[~(df["CANT"] < 30) & ~(df["NOMBRE_VENDEDOR"] == "ALFREDO CANELA")]
filtro10
filtro10.to_csv("Filtro10.csv")